### ISSUE TITLE
Ooops, hab da was falsches per PR reingepusht

### ISSUE THREAD

**Issue by jstsmthrgk** [finga/rc3-cccsbg#7]
ähm, bitte einfach in der Zeile 28 https://github.com/finga/rc3-cccsbg/blob/ef795525f321b76ae39c565ad8158f4090764447/.github/workflows/build-and-deploy.yml#L28 das `hbf/*.json`weglöschen, dann funktioniert das script auch

sorry

**Comment by finga** [comment]
Sollte erledigt sein, danke!

**Comment by jstsmthrgk** [comment]
ahhhh, dieser verdammte `main` statt `master`
https://github.com/finga/rc3-cccsbg/blob/ca3b227bbd1501b2f74aabe957dc076339df43af/.github/workflows/build-and-deploy.yml#L37
https://github.com/finga/rc3-cccsbg/blob/ca3b227bbd1501b2f74aabe957dc076339df43af/.github/workflows/build-and-deploy.yml#L45
an diesen beiden stellen sollte `main` statt `master` stehen

achtung! das `master` hier sollte so bleiben:
https://github.com/finga/rc3-cccsbg/blob/ca3b227bbd1501b2f74aabe957dc076339df43af/.github/workflows/build-and-deploy.yml#L30

**Comment by finga** [comment]
xD ich glaub jetzt passts
