### ISSUE TITLE
Ich glaube Github pages läuft am falschen Branch

### ISSUE THREAD

**Issue by jstsmthrgk** [finga/rc3-cccsbg#9]
Äh, Github Pages sollte auf den `gh-pages` branch eingestellt sein, nicht auf irgendeinen anderen.

**Comment by jstsmthrgk** [comment]
Das ist noch immer der Fall, unter https://finga.github.io/rc3-cccsbg/bahnsteig.json ist der inhalt vom `main` branch und nicht vom `gh-pages` branch. (Das ganze funktioniert sowieso so, dass alle änderungen in `main` automatisch nach `gh-pages` hinübersynchronisiert werden, dabei werden halt die links aufgelöst und so und wenn das nicht gemacht wird, funktioniert die bahn nicht, darum muss github pages auf den richtigen branch eingstellt sein)

**Comment by finga** [comment]
Habs gerade umgestellt und ich bild mir ein, dass es jetzt passen sollte..
